### ISSUE TITLE
Unable to change SSID and a password

### ISSUE THREAD

**Issue by brother-of-steel** [Anthony96922/mt7601u-ap#5]
I compile it on the latest hardened stable kernel in Gentoo, after some tweaks (_-Wno-implicit-function-declaration -Wno-incompatible-pointer-types_) I managed this module to work, but... I am unable to change SSID and the password, looks like the config file is not read, after setting the **ra0** state to up, there a new network called **HT_01**, with security set to OPEN. What I am missed?

**Comment by sxyandapp** [comment]
Have you solved it ?? waiting  answer.....

**Comment by sxyandapp** [comment]
以下内容都是基于树莓派3b及其当前的最新系统进行的：
经过测试，楼主的这个版本似乎不能正常读取配置文件，不仅导致设定的wifi热点名称和密码不生效，还会导致在ifconfig中产生很多个raN这样的网卡，而且也会产生很多个热点。。。我尝试了修改楼主的源码，但没有成功。最后，我在github上找到了一个正常的版本，可正常编译，也可正常使用，不敢私享，特此分享：https://github.com/PolyVection/mt7601u-ap
另外，我会在我的博客的树莓派分类中详细叙述我的测试过程：http://blog.csdn.net/sxyandapp

**Comment by combat007** [comment]
I am facing the same problem, Here is my scenario
1.Directory created and file kept /etc/Wireless/RT2870AP/RT2870AP.dat , config for file contents are
#The word of "Default" must not be removed
Default
CountryRegion=5
CountryRegionABand=7
CountryCode=TW
BssidNum=1
SSID=HD_MESH_1
WirelessMode=9
TxRate=0
Channel=11
BasicRate=15
BeaconPeriod=100
DtimPeriod=1
TxPower=100
DisableOLBC=0
BGProtection=0
TxAntenna=
RxAntenna=
TxPreamble=0
RTSThreshold=2347
FragThreshold=2346
TxBurst=1
PktAggregate=0
TurboRate=0
WmmCapable=0
APSDCapable=0
DLSCapable=0
APAifsn=3;7;1;1
APCwmin=4;4;3;2
APCwmax=6;10;4;3
APTxop=0;0;94;47
APACM=0;0;0;0
BSSAifsn=3;7;2;2
BSSCwmin=4;4;3;2
BSSCwmax=10;10;4;3
BSSTxop=0;0;94;47
BSSACM=0;0;0;0
AckPolicy=0;0;0;0
NoForwarding=0
NoForwardingBTNBSSID=0
HideSSID=0
StationKeepAlive=0
ShortSlot=1
AutoChannelSelect=0
IEEE8021X=0
IEEE80211H=0
CSPeriod=10
WirelessEvent=0
IdsEnable=0
AuthFloodThreshold=32
AssocReqFloodThreshold=32
ReassocReqFloodThreshold=32
ProbeReqFloodThreshold=32
DisassocFloodThreshold=32
DeauthFloodThreshold=32
EapReqFooldThreshold=32
PreAuth=0
AuthMode=WPA2PSK
EncrypType=TKIP;AES
RekeyInterval=0
RekeyMethod=DISABLE
PMKCachePeriod=10
WPAPSK=1234567890
DefaultKeyID=1
Key1Type=0
Key1Str=
Key2Type=0
Key2Str=
Key3Type=0
Key3Str=
Key4Type=0
Key4Str=
HSCounter=0
AccessPolicy0=0
AccessControlList0=
AccessPolicy1=0
AccessControlList1=
AccessPolicy2=0
AccessControlList2=
AccessPolicy3=0
AccessControlList3=
WdsEnable=0
WdsEncrypType=NONE
WdsList=
WdsKey=
RADIUS_Server=192.168.2.3
RADIUS_Port=1812
RADIUS_Key=ralink
own_ip_addr=192.168.5.234
EAPifname=br0
PreAuthifname=br0
HT_HTC=0
HT_RDG=0
HT_EXTCHA=0
HT_LinkAdapt=0
HT_OpMode=0
HT_MpduDensity=5
HT_BW=1
HT_AutoBA=1
HT_AMSDU=0
HT_BAWinSize=64
HT_GI=1
HT_MCS=33
MeshId=MESH
MeshAutoLink=1
MeshAuthMode=OPEN
MeshEncrypType=NONE
MeshWPAKEY=
MeshDefaultkey=1
MeshWEPKEY=
WscManufacturer=
WscModelName=
WscDeviceName=
WscModelNumber=
WscSerialNumber=
RadioOn=1
PMFMFPC=0
PMFMFPR=0
PMFSHA256=0

2. Module compiled and inserted to kernel succesfully ra0 link came up before that isc-dhcp-server running successfully ip for the ra0 link is 192.168.42.1/255.255.255.0 working good

3. iwconfig ra0 
output:
ra0     IEEE 802.11  ESSID:"HT_AP0"  
          Mode:Master  Channel:1  Access Point: 70:F1:1C:25:50:A0   
          Bit Rate=54 Mb/s 

Since you can see the ESSID is still HT_AP0 and on android mobile I can only see the same essid with not security and on selecting it nothing happens.

Kindly Help.

**Comment by Anthony96922** [comment]
This driver should work properly on newer kernels now.
